#ifndef SEARCHANDTRACKINGTARGETLIBRARY_GLOBAL_H
#define SEARCHANDTRACKINGTARGETLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SEARCHANDTRACKINGTARGETLIBRARY_LIBRARY)
#  define SEARCHANDTRACKINGTARGETLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SEARCHANDTRACKINGTARGETLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SEARCHANDTRACKINGTARGETLIBRARY_GLOBAL_H
